### ISSUE TITLE
error runing plugin

### ISSUE THREAD

**Issue by Miriambarros** [kapoorlab/vollseg-napari#3]
Hi!

Today, i installed napari and then this plugin (from this plugin menu). After the installation sucecced, i go to the plugin menu and click on  the vollseg-napari button and get the following error: 

Failed to import command at 'vollseg_napari._dock_widget:plugin_wrapper_vollseg': No module named 'magicgui.events'

**Comment by kapoorlab** [comment]
Hi,

Since vollseg napari uses magicgui to create the widgets you would need to have magic gui installed in the anaconda environment where you are launching Napari from. You can install magic gui in that environment using pip install magicgui, see the package [here](https://pypi.org/project/magicgui/). Hope this solves your issue.

**Comment by Chagui-** [comment]
I think the problem is that the library is not compatible with magicgui 0.4.0, as it removes the events.py  file that is being used here. 
I found [this migration guide](https://github.com/napari/magicgui/blob/3eddd9b66028e2dbecfe81b74c672efe50bd4306/docs/api/v0_3_0.md).

As stated there: 
```
Existing code using callbacks with a single positional argument will continue to receive a single Event object (and a
warning will be shown, until v0.4.0 where it will become an error).
```

**Comment by kapoorlab** [comment]
Ah indeed I can reproduce the error you are getting with the magic gui 0.4.0, am updating my code now to migrate to being compatible with the new version.

**Comment by kapoorlab** [comment]
Hello, I released new versions of vollseg and vollseg-napari, pip install the new versions and see if you are able to run it now?

**Comment by Miriambarros** [comment]
It's working!!!!!
Thank you so much!
