### ISSUE TITLE
local variable 'maximage' referenced before assignment

### ISSUE THREAD

**Issue by orena1** [kapoorlab/vollseg-napari#7]
Hi, I'm trying the run the plugin on these data:
[image000.zip](https://github.com/Kapoorlabs-CAPED/vollseg-napari/files/11325871/image000.zip)
default settings:
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/8983713/234375592-1731e0f7-3a5d-4eb4-a7eb-980756c1660d.png">

And I get this error:
```python
~\anaconda3\lib\site-packages\vollseg\utils.py in VollSeg3D(image=<class 'numpy.ndarray'> (30, 379, 460) float32, unet_model=UNET(Embryo Cell Model (3D)): ZYXC → ZYXC
├─ Dir..., train_reduce_lr={'patience': 5, 'factor': 0.5}), star_model=StarDist3D(Carcinoma_cells): ZYXC → ZYXC
├─ Dire...5, 'patience': 40, 'min_delta': 0}, use_gpu=True), axes='ZYX', noise_model=CARE(Denoise_3D_cells): ZYXC → ZYXC
├─ Directory... train_reduce_lr={'patience': 10, 'factor': 0.5}), roi_model=MASKUNET(Unet_Arabidopsis_Mask): ZYXC → ZYXC
├─ ..., train_reduce_lr={'patience': 5, 'factor': 0.5}), prob_thresh=0.5, nms_thresh=0.4, min_size_mask=1.0, min_size=1.0, max_size=10000000.0, n_tiles=(1, 1, 1), UseProbability=True, ExpandLabels=False, dounet=True, seedpool=True, donormalize=True, lower_perc=1.0, upper_perc=99.8, slice_merge=False)
   4270         elif model_dim == len(image.shape):
   4271             Segmented = roi_model.predict(
-> 4272                 maximage.astype("float32"), "YX", n_tiles=n_tiles
        maximage.astype = undefined
        n_tiles = (1, 1, 1)
   4273             )
   4274             try:

UnboundLocalError: local variable 'maximage' referenced before assignment

```
Any tips?
Thanks,
Oren

**Comment by kapoorlab** [comment]
Hello,

Thank you for bringing it to my attention, in our use cases we have so far used a 2D U-Net model as MASKUNET for 3D images so we did not notice this little bug hiding at that line which we fixed in the version 29.9.3, I tried it using some models I had and using a 3D U-Net model as the Mask model that it ran without error, you may just need to train your own models for best results.

See my run example result in this attached screenshot.
![example](https://user-images.githubusercontent.com/16645600/234391722-380329c9-fc9f-4772-8b7b-9fa9f5175f36.png)

**Comment by orena1** [comment]
Thanks for the correction @kapoorlab.
Yeah I have some labeled data to finetune on, BTW, the example folder which is referred in the  [README ](https://github.com/Kapoorlabs-CAPED/VollSeg) does not exists:
https://github.com/Kapoorlabs-CAPED/VollSeg/blob/main/examples/Train/ColabN2VTrain.ipynb

**Comment by kapoorlab** [comment]
Yes indeed, the examples folder have moved and will re-appear after a major update later this year, those were outdated and I need to fix the README also to reflect that. Thanks again for your help.

**Comment by orena1** [comment]
Thanks a lot, so currently I don't really have a way to fine-tune the models, meaning that I need to wait for the later this year for trying your plugin?

**Comment by kapoorlab** [comment]
I run a company where I work with researchers in a paid collaboration to create tailored models, workflow and customized scripts for them, that is one option the other one being waiting for later this year when we plan to release more models and updated documentation and workflow Napari plugins as a part of this year's CZI grant cycle.

**Comment by orena1** [comment]
Ok, thank you, good luck

**Comment by kapoorlab** [comment]
Thank you, till next time.
