### ISSUE TITLE
dependency on torchvision, but missing when installed

### ISSUE THREAD

**Issue by TimMonko** [kapoorlab/vollseg-napari#8]
I reproduced this with:
```
mamba create -n vollseg python=3.9
mamba activate vollseg
pip install tensorflow
pip install vollseg-napari
```
Attempting to open a sample image or the vollseg plugin resulted in `RuntimeError: Failed to import command at __command location__: No module named 'torchvision'`

**Comment by kapoorlab** [comment]
Yes in the newer version of vollseg there are dependencies on pytorch that I have not included in the setup file, in your current environment if you do 

`
pip install torch
pip install torchvision
pip install torchaudio
`

Your code should start working, I will update the setup file in the meantime for the next release, thanks for pointing this out.
